[#3526] Add support for MSI to JS samples and generators - QnA samples
southworkscom/BotBuilder-Samples pull request #355
Opened 2021-10-22 20:12 UTC by MartinLuccanera

Addresses # 3526

## Description
This PR updates the QnA sample bots adding support for MSI and SingleTenant App types.

### Detailed Changes
- Updated the **_botbuilder_** dependency to the RC0 version.
- Updated **_index.js_** to pass the new parameters AppType and AppTenantId to the 
- Added the new settings _MicrosoftAppType_ and _MicrosoftAppTenantId_ to the **_env_** file.

This PR updates the following samples:
- JavaScript
   - 11.qnamaker
   - 49.qnamaker-all-features.

## Testing
The following images show one of the bots working with User Assigned MSI configuration.
![image](https://user-images.githubusercontent.com/18757147/138517116-dd1b363d-f009-4afc-a03e-382122bff9fa.png)

2021-10-22 20:15 UTC, ceciliaavila requested changes

2021-10-22 20:15 UTC, ceciliaavila commented on samples/javascript_nodejs/11.qnamaker/.env
> +DefaultAnswer=
Why did you add this line?

2021-10-22 20:16 UTC, sw-joelmut requested changes

2021-10-22 20:16 UTC, sw-joelmut commented on samples/javascript_nodejs/11.qnamaker/.env
> +DefaultAnswer=
The DefaultAnswer is not used in this project

2021-10-22 20:16 UTC, sw-joelmut commented on samples/javascript_nodejs/11.qnamaker/index.js
> +    MicrosoftAppType: process.env.MicrosoftAppType,
Move the MicrosoftAppType below the MicrosoftAppPassword like we did for the rest of the samples

2021-10-22 20:23 UTC, ceciliaavila approved these changes

2021-10-26 16:44 UTC, ceciliaavila commented
Promoted to MS in PR# 3557

2021-10-26 16:44 UTC, closed without merging